                                                                                                               
                                                                                                               			public class LeapYear {                                                                                                           
                                                                                                                                                                kmkmlmlml    JJ   dd                                           
                                                                                                                                int five(){ return 5; }                                                                                                             
                                                                                                               	        public int six(){ return 5;}                                                                                    
                                                                                                               			}                                                                                                               
                                                                                                               		                                                                                                               
                                                                                                                                                                                                                             
                                                                                                                                                                                                                           
                                                                                                                                                                                                                         
                                                                                                                                                                                                                       
                                                                                                                                                                                                                     
                                                                                                                                                                                                                   
                                                                                                                                                                                                                 
                                                                                                                                                                                                               
                                                                                                                                                                                                             
                                                                                                                                                                                                           
                                                                                                                                                                                                         
                                                                                                                                                                                                       
                                                                                                                                                                                                     
                                                                                                                                                                                                   
                                                                                                                                                                                                 
                                                                                                                                                                                               
                                                                                                                                                                                             
                                                                                                                                                                                           
                                                                                                                                                                                         
                                                                                                                                                                                       
                                                                                                                                                                                     
                                                                                                                                                                                   
                                                                                                                                                                                 
                                                                                                                                                                               
                                                                                                                                                                             
                                                                                                                                                                           
                                                                                                                                                                         
                                                                                                                                                                       
                                                                                                                                                                     
                                                                                                                                                                   
                                                                                                                                                                 
                                                                                                                                                               
                                                                                                                                                             
                                                                                                                                                           
                                                                                                                                                         
                                                                                                                                                       
                                                                                                                                                     
                                                                                                                                                   
                                                                                                                                                 
                                                                                                                                               
                                                                                                                                             
                                                                                                                                           
                                                                                                                                         
                                                                                                                                       
                                                                                                                                     
                                                                                                                                   
                                                                                                                                 
                                                                                                                               
                                                                                                                             
                                                                                                                           
                                                                                                                         
                                                                                                                       
                                                                                                                     
                                                                                                                   
                                                                                                                 
                                                                                                               
                                                                                                             
                                                                                                           
                                                                                                         
                                                                                                       
                                                                                                     
                                                                                                   
                                                                                                 
                                                                                               
                                                                                             
                                                                                           
                                                                                         
                                                                                       
                                                                                     
                                                                                   
                                                                                 
                                                                               
                                                                             
                                                                           
                                                                         
                                                                       
                                                                     
                                                                   
                                                                 
                                                               
                                                             
                                                           
                                                         
                                                       
                                                     
                                                   
                                                 
                                               
                                             
                                           
                                         
                                       
                                     
                                   
                                 
                               
                             
                           
                         
                       
                     
                   
                 
               
             
           
         
       
     
   
 