public class Peter{                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                            
                                                                                                            Swegat sw = new Swegat();                                                                                                 
                                                                                                                                                                                          
                                                                                                                                                          
                                                                                                                                          
                                                                                                            public int five(){                                                                                             
                                                                                                            int a = 0;                                                                                               
                                                                                                            for(int i = 0; i <= 10; i++)                                                                                             
                                                                                                            a =i;                                                                                              
                                                                                                            return a;                                                                                             
                                                                                                             }                                                                                                                                                                      
                                                                                                                                                                                          
                                                                                                            public int six(){ return 58; }                                                                                                                                          
                                                                                                            public int sev(){ return sw.seven(); }                                                                                                                                                        
                                                                                                                                                                                                                                                                  
                                                                                                         }                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                               
                                                                                                                                                                                                                             
                                                                                                                                                                                                                           
                                                                                                                                                                                                                         
                                                                                                                                                                                                                       
                                                                                                                                                                                                                     
                                                                                                                                                                                                                   
                                                                                                                                                                                                                 
                                                                                                                                                                                                               
                                                                                                                                                                                                             
                                                                                                                                                                                                           
                                                                                                                                                                                                         
                                                                                                                                                                                                       
                                                                                                                                                                                                     
                                                                                                                                                                                                   
                                                                                                                                                                                                 
                                                                                                                                                                                               
                                                                                                                                                                                             
                                                                                                                                                                                           
                                                                                                                                                                                         
                                                                                                                                                                                       
                                                                                                                                                                                     
                                                                                                                                                                                   
                                                                                                                                                                                 
                                                                                                                                                                               
                                                                                                                                                                             
                                                                                                                                                                           
                                                                                                                                                                         
                                                                                                                                                                       
                                                                                                                                                                     
                                                                                                                                                                   
                                                                                                                                                                 
                                                                                                                                                               
                                                                                                                                                             
                                                                                                                                                           
                                                                                                                                                         
                                                                                                                                                       
                                                                                                                                                     
                                                                                                                                                   
                                                                                                                                                 
                                                                                                                                               
                                                                                                                                             
                                                                                                                                           
                                                                                                                                         
                                                                                                                                       
                                                                                                                                     
                                                                                                                                   
                                                                                                                                 
                                                                                                                               
                                                                                                                             
                                                                                                                           
                                                                                                                         
                                                                                                                       
                                                                                                                     
                                                                                                                   
                                                                                                                 
                                                                                                               
                                                                                                             
                                                                                                           
                                                                                                         
                                                                                                       
                                                                                                     
                                                                                                   
                                                                                                 
                                                                                               
                                                                                             
                                                                                           
                                                                                         
                                                                                       
                                                                                     
                                                                                   
                                                                                 
                                                                               
                                                                             
                                                                           
                                                                         
                                                                       
                                                                     
                                                                   
                                                                 
                                                               
                                                             
                                                           
                                                         
                                                       
                                                     
                                                   
                                                 
                                               
                                             
                                           
                                         
                                       
                                     
                                   
                                 
                               
                             
                           
                         
                       
                     
                   
                 
               
             
           
         
       
     
   
 