public class Swegat{                                                                                                                                                    
                                                                                                                                                                                                                                    
                                                                           public int seven(){ return 7; }                                                                                   
                                                                                                                                                                                               
                                                                          }                                                                                                                                                    
                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                               
                                                                                                                                                                                                                             
                                                                                                                                                                                                                           
                                                                                                                                                                                                                         
                                                                                                                                                                                                                       
                                                                                                                                                                                                                     
                                                                                                                                                                                                                   
                                                                                                                                                                                                                 
                                                                                                                                                                                                               
                                                                                                                                                                                                             
                                                                                                                                                                                                           
                                                                                                                                                                                                         
                                                                                                                                                                                                       
                                                                                                                                                                                                     
                                                                                                                                                                                                   
                                                                                                                                                                                                 
                                                                                                                                                                                               
                                                                                                                                                                                             
                                                                                                                                                                                           
                                                                                                                                                                                         
                                                                                                                                                                                       
                                                                                                                                                                                     
                                                                                                                                                                                   
                                                                                                                                                                                 
                                                                                                                                                                               
                                                                                                                                                                             
                                                                                                                                                                           
                                                                                                                                                                         
                                                                                                                                                                       
                                                                                                                                                                     
                                                                                                                                                                   
                                                                                                                                                                 
                                                                                                                                                               
                                                                                                                                                             
                                                                                                                                                           
                                                                                                                                                         
                                                                                                                                                       
                                                                                                                                                     
                                                                                                                                                   
                                                                                                                                                 
                                                                                                                                               
                                                                                                                                             
                                                                                                                                           
                                                                                                                                         
                                                                                                                                       
                                                                                                                                     
                                                                                                                                   
                                                                                                                                 
                                                                                                                               
                                                                                                                             
                                                                                                                           
                                                                                                                         
                                                                                                                       
                                                                                                                     
                                                                                                                   
                                                                                                                 
                                                                                                               
                                                                                                             
                                                                                                           
                                                                                                         
                                                                                                       
                                                                                                     
                                                                                                   
                                                                                                 
                                                                                               
                                                                                             
                                                                                           
                                                                                         
                                                                                       
                                                                                     
                                                                                   
                                                                                 
                                                                               
                                                                             
                                                                           
                                                                         
                                                                       
                                                                     
                                                                   
                                                                 
                                                               
                                                             
                                                           
                                                         
                                                       
                                                     
                                                   
                                                 
                                               
                                             
                                           
                                         
                                       
                                     
                                   
                                 
                               
                             
                           
                         
                       
                     
                   
                 
               
             
           
         
       
     
   
 