 import org.junit.Test;                                                                                                                                                                                  
                                                                                                        import static org.junit.Assert.*;                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                           
                                                                                                        public class TesterPester {                                                                                                                                                                                          
                                                                                                                                              	                                                                                                                                                 
                                                                                                         @Test	                                                                                                                                                                                  
                                                                                                          public void testEight(){                                                                                                                                                                                  
                                                                                                          Peter peter = new Peter();                                                                                                                                                                                   
                                                                                                          assertEquals(peter.sev(),57);                                                                                                                                                                                   
                                                                                                          }                                                                                                                                                                
                                                                                                       }                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                               
                                                                                                                                                                                                                             
                                                                                                                                                                                                                           
                                                                                                                                                                                                                         
                                                                                                                                                                                                                       
                                                                                                                                                                                                                     
                                                                                                                                                                                                                   
                                                                                                                                                                                                                 
                                                                                                                                                                                                               
                                                                                                                                                                                                             
                                                                                                                                                                                                           
                                                                                                                                                                                                         
                                                                                                                                                                                                       
                                                                                                                                                                                                     
                                                                                                                                                                                                   
                                                                                                                                                                                                 
                                                                                                                                                                                               
                                                                                                                                                                                             
                                                                                                                                                                                           
                                                                                                                                                                                         
                                                                                                                                                                                       
                                                                                                                                                                                     
                                                                                                                                                                                   
                                                                                                                                                                                 
                                                                                                                                                                               
                                                                                                                                                                             
                                                                                                                                                                           
                                                                                                                                                                         
                                                                                                                                                                       
                                                                                                                                                                     
                                                                                                                                                                   
                                                                                                                                                                 
                                                                                                                                                               
                                                                                                                                                             
                                                                                                                                                           
                                                                                                                                                         
                                                                                                                                                       
                                                                                                                                                     
                                                                                                                                                   
                                                                                                                                                 
                                                                                                                                               
                                                                                                                                             
                                                                                                                                           
                                                                                                                                         
                                                                                                                                       
                                                                                                                                     
                                                                                                                                   
                                                                                                                                 
                                                                                                                               
                                                                                                                             
                                                                                                                           
                                                                                                                         
                                                                                                                       
                                                                                                                     
                                                                                                                   
                                                                                                                 
                                                                                                               
                                                                                                             
                                                                                                           
                                                                                                         
                                                                                                       
                                                                                                     
                                                                                                   
                                                                                                 
                                                                                               
                                                                                             
                                                                                           
                                                                                         
                                                                                       
                                                                                     
                                                                                   
                                                                                 
                                                                               
                                                                             
                                                                           
                                                                         
                                                                       
                                                                     
                                                                   
                                                                 
                                                               
                                                             
                                                           
                                                         
                                                       
                                                     
                                                   
                                                 
                                               
                                             
                                           
                                         
                                       
                                     
                                   
                                 
                               
                             
                           
                         
                       
                     
                   
                 
               
             
           
         
       
     
   
 